### ISSUE TITLE
Language specific characters are not correct when uploading ontology

### ISSUE THREAD

**Issue by gregid** [inovexcorp/mobi#11]
Try adding new ontology by uploading doap.rdf from:
https://github.com/ewilderj/doap/tree/master/schema
e.g. portuguese description:
`Vocabulário de descrição de um Projeto`
becomes
`VocabulÃ¡rio de descriÃ§Ã£o de um Projeto`

Adding special characters manually in mobi works fine, so the problem with encoding is only with the upload.

**Comment by gregid** [comment]
I have just been checking the new version of mobi but the problem persists - the uploaded files seem to be losing their encoding. I am not sure about other OSs but it is definitely a problem on Windows.

**Comment by mnmercer** [comment]
Hello @gregid . I believe your issue is coming from outside of Mobi and is an issue with the encoding of the file on your Windows machine. On my Mac, I went to the repository you linked, opened up the raw view of the file you mentioned, copied the content into my developer text editor (Visual Studio Code), saved it, then uploaded the file into Mobi and the special characters are displaying fine. 

<img width="1680" alt="Screen Shot 2019-10-07 at 2 16 36 PM" src="https://user-images.githubusercontent.com/9361260/66337428-1c4a7880-e90d-11e9-8586-cfb4fcd51e30.png">

How did you save the file onto your Windows machine?

**Comment by gregid** [comment]
I thought this may be an OS related issue since no one else noticed it. Previously I had the repo cloned, this time I repeated exactly your steps (raw -> copy/paste -> save in VS code) the encoding is also UTF-8 which should be fine. Here is a screenshot:

![mobi-lost-encoding](https://user-images.githubusercontent.com/7010458/66344403-1923ac80-e94e-11e9-81c1-796f5d7ceda7.png)

**Comment by skahmann** [comment]
Hi @gregid I am also trying to recreate the problem you are seeing. I am using the latest version of the 1.16 release ([link](https://mobi.inovexcorp.com/features/#download)). I uploaded this file to the ontology editor: 

[doap.rdf.zip](https://github.com/inovexcorp/mobi/files/4462330/doap.rdf.zip)

and I'm seeing the correct rendering of characters:

![image](https://user-images.githubusercontent.com/2256862/79005036-015afa00-7b24-11ea-906a-5e0df5c966de.png)

**Comment by gregid** [comment]
Hi @skahmann - which operating system have you used for this test? 
I will try to test it again with the latest version (on Windows)

**Comment by skahmann** [comment]
I am using macOS Catalina 10.15.4.

**Comment by gregid** [comment]
This problem was only Windows specific - I will let you know if it persists with latest version.

**Comment by skahmann** [comment]
Sounds good. I can test on Windows as well, but I probably don't have the same locale settings you are using which may affect the results.

**Comment by skahmann** [comment]
Ah, I was able to recreate this on a test Windows machine. I'll see if I can find the problem...

**Comment by gregid** [comment]
Unfortunately the problem persists on 1.16.65.
Edit: yep the same here

**Comment by skahmann** [comment]
Apologies for the delay on this issue. We've got all the info we need to reproduce the problem and we've got a bug filed to be included in the next release. I'll update this ticket when the fix is available.

**Comment by gregid** [comment]
Great to hear! Thank you.

**Comment by gregid** [comment]
I have just checked the 1.17.75 version and it now works as expected.
