### ISSUE TITLE
Unable to deploy mobi as docker image behind an nginx proxy

### ISSUE THREAD

**Issue by dark06** [inovexcorp/mobi#14]
I tried executing the steps as described in the documentation below
https://mobi.inovexcorp.com/docs/#installing_the_docker_image

using Docker on my local machine I get a certification error but ohterwise everything is working fine
however when deploying the docker image on a ubuntu server running docker deamon and exposing the port behind an nginx reverse proxy, I get no paged displayed and the connection terminates after some time.

I double checked that the container gets the request from the client throught the nginx reverse proxy. I am guessing it has soemthing to do with the SSL encryption.
Is there a way to disable such and listen on HTTP instead of HTTPS

**Comment by dark06** [comment]
just wanted to check on this issue
is there a way to disable the SSL connection?

**Comment by skahmann** [comment]
I would recommend setting your Nginx proxy to correctly proxy UI and REST requests to the server. More information on the knowledge base article: https://inovexirad.atlassian.net/servicedesk/customer/kb/view/1197342735

**Comment by dark06** [comment]
Thanks! The following snippet did the trick
```
location / {
      proxy_pass https://localhost:8443 ;
   }
```

I tested it with version `1.17.75` and `1.16.65` and it only works with `1.16.65`
