### ISSUE TITLE
Unable to build MatOnto from 'mvn clean install'

### ISSUE THREAD

**Issue by rayaprolu143** [inovexcorp/mobi#2]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:51 h
[INFO] Finished at: 2017-09-23T01:58:56+05:30
[INFO] Final Memory: 34M/336M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (integration-test) on project matonto-parent: Execution integration-test of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: Plugin org.apache.maven.plugins:maven-failsafe-plugin:2.18.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.surefire:surefire-api:jar:2.18.1 from/to matonto.hanover.releases (http://nexus.matonto.org/repository/matonto-public/): Connect to nexus.matonto.org:80 [nexus.matonto.org/50.246.88.26] failed: Connection timed out (Connection timed out) -> [Help 1]

Could anyone help me resolve the issue?

**Comment by skahmann** [comment]
In your error message it looks like maven is trying to retrieve surefire-api from the matonto nexus repository. The matonto nexus repository only has matonto artifacts so that will fail, but more importantly it was actually unable to connect to the repo in the first place. Are you able to resolve http://nexus.matonto.org/ in a browser?

**Comment by rayaprolu143** [comment]
Yes, you are right, I am unable to resolve it in the browser.

**Comment by skahmann** [comment]
There may be an issue with the network configuration for our server or firewall. I'll look into this and let you know when it's fixed.

**Comment by rayaprolu143** [comment]
Thank You.

**Comment by skahmann** [comment]
Thank you for your patience! We just cut the 1.9 release today which has some configuration updates to coincide with some infrastructure improvements. These changes should resolve your issue. Let me know if it helps.

**Comment by rayaprolu143** [comment]
I downloaded the latest version and ran "mvn clean install" in the directory and following is the message popped up on the screen. Could you please tell me how to rectify it?


BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 h
[INFO] Finished at: 2017-10-22T16:54:41+05:30
[INFO] Final Memory: 91M/837M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project web: Could not resolve dependencies for project com.mobi:web:bundle:1.9.44: Could not transfer artifact org.osgi:osgi.cmpn:jar:6.0.0 from/to central (https://repo.maven.apache.org/maven2): Connection timed out (Read failed) -> [Help 1]

**Comment by skahmann** [comment]
I don't think we've seen this issue before. It looks like it can't retrieve a jar from Maven Central. Can you download this directly? https://repo.maven.apache.org/maven2/org/osgi/osgi.cmpn/6.0.0/osgi.cmpn-6.0.0.jar

Can you attach the build log from the entire web module?

**Comment by rayaprolu143** [comment]
I did not understand what you mean by "Can you attach the build log from the entire web module?". Could you elaborate on it?

**Comment by skahmann** [comment]
I'd like to see the console output from `[INFO] Building com.mobi.web <version>` down to this error so I can see all the output for this module in the project.

**Comment by rayaprolu143** [comment]
The source is built successfully. I just ran the command again and again, it worked! But, it is asking me for login details?

**Comment by skahmann** [comment]
Login details for the webapp? Should be admin:admin. More information here: https://mobi.inovexcorp.com/docs/#installing_from_the_distribution

**Comment by rayaprolu143** [comment]
Thanks a lot for patiently answering all my questions.
