### ISSUE TITLE
The ability to scroll horizontally on the tree pane and the ability to widen the pane

### ISSUE THREAD

**Issue by kbserm** [inovexcorp/mobi#4]

**Comment by skahmann** [comment]
We are working on a few improvements in 1.13 that should help to address this. Horizontal scrolling will be included. Resizing this panel (and other UI customization) is something we are looking into, but will require quite a bit more work so I wouldn't expect that in the short term.

**Comment by mnmercer** [comment]
@kbserm We have just included a fix in 1.13 which includes horizontal scrolling of the hierarchies. Keep an eye out for that release soon!

**Comment by mnmercer** [comment]
@kbserm Closing this as we just released 1.13 which includes the fix.
