### ISSUE TITLE
Does Mobi ontology editor support drag-n-drop to adjust class hierarchy?

### ISSUE THREAD

**Issue by lifan0127** [inovexcorp/mobi#5]
In the class hierarchy panel (or the SKOS concept panel), should we be able to drag and drop items to re-arrange the hierarchy?

**Comment by skahmann** [comment]
We currently do not support drag and drop of hierarchy items, but this is an often requested feature. We will investigate this feature for a future release. In the meantime, you can use the subclass axiom (or broader/narrower relationships for SKOS) to modify the hierarchy.

**Comment by lifan0127** [comment]
Thanks!
