### ISSUE TITLE
Imports that have overlapping ontologies seem causing issue

### ISSUE THREAD

**Issue by kbserm** [inovexcorp/mobi#8]
I and Minchul (please contact minchul.lee@nist.gov for further conversation) encounter a problem when our ontology has had BFO imported and then we were importing the Information Content Entity (ICE) ontology. ICE also imports BFO. And the result of the ICE import is that all classes we created under BFO earlier disappeared.

**Comment by skahmann** [comment]
Hi Serm, we'll take a look at this and see if we can get a fix ASAP.

**Comment by skahmann** [comment]
Unable to reproduce. Let us know if you see this again.
