### ISSUE TITLE
Request: Add Polish, @pl to the list of languages

### ISSUE THREAD

**Issue by gregid** [inovexcorp/mobi#9]
Also is there any reason why adding language tags is limited to only a handful in the first place?
Why not make it a free field with suggestions?

EDIT: If for some technical reason it must be a dropdown then the list of available values should be editable in Administration view.

**Comment by mnmercer** [comment]
Hi @gregid ! We are releasing 1.15 very soon which will include support for all the languages listed [here](https://www.w3schools.com/tags/ref_language_codes.asp), include `@pl`. The source code for this version is now on the `master` and `develop` in this project and the pre-built binaries will be available on our [website](https://mobi.inovexcorp.com/) by the end of the day.

**Comment by gregid** [comment]
That's great to hear! Looking forward to the new release.
